---
title: "eSports Data Visualization"
author: "Nicholas Rivera"
date: "3/19/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
```


# Data Importation

```{r}
OverwatchData <- read.csv(file = "../data/overwatch_competitive_6_months.csv") %>% 
    tibble() %>% 
    clean_names()
OverwatchData %>% head()
```

# Bar Plot

```{r}
BarPlot <- OverwatchData %>% 
    ggplot(mapping = aes(x = hero, y = pick_rate_a, fill = hero_type)) + 
    geom_col(width = 0.75, color = "black") +
    facet_wrap(. ~ system) + 
    scale_fill_manual(values = c("orange", "red", "green", "blue")) +
    scale_y_continuous(labels = scales::percent) + 
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90)) + 
    labs(
        title = "Overwatch Characters Pick Rate, Competitive Play", 
        subtitle = "Barchart: Percentage per System (6 Months)", 
        x = "Character",
        y = "Pick Rate Percentage",
        fill = "Hero Type", 
        caption = "Source: https://www.overbuff.com/heroes"
    )

BarPlot
```

# Dot Plot

```{r}
DotPlot <- OverwatchData %>% 
    ggplot(mapping = aes(x = win_rate, y = hero, fill = system)) + 
    geom_point(size = 2, shape = 21, color = "black")  +
    geom_segment(mapping = aes(yend = hero), xend = 0, color = "black") +
    scale_y_discrete(limits = rev) +
    scale_x_continuous(labels = scales::percent) + 
    facet_wrap(. ~ system) + 
    theme_minimal() + 
    theme(axis.line.y = element_line(colour = "black", size = 1)) +
    theme(axis.text.x = element_text(angle = 45)) + 
    labs(
        title = "Overwatch Character Win Rates, Competitive Play", 
        subtitle = "Dotplot: Win Percentage by System (6 Months)", 
        x = "Percentage", 
        y = "Hero", 
        fill = "System", 
        caption = "Source: https://www.overbuff.com/heroes"
    )

DotPlot
```

# Image Export

```{r}
ggsave(filename = "../images/barplot.png", plot = BarPlot)
ggsave(filename = "../images/dotplot.png", plot = DotPlot)
```

